nodeLinker: node-modules

npmAlwaysAuth: false

npmRegistryServer: 'https://registry.yarnpkg.com'
npmAuditRegistry: 'https://registry.yarnpkg.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@/plugin-cache-dir.cjs
    spec: '@/plugin-cache-dir'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
